package it.unibo.disi.spaf.common.exceptions;

/**
 * {@link StreamProcessingException} is the top-level exception type generated by SPAF.
 */
public class StreamProcessingException extends RuntimeException {
	
	private final static long serialVersionUID = 1L;

	public StreamProcessingException(String message) {
		super(message);
	}

	public StreamProcessingException(String message, Throwable cause) {
		super(message, cause);
	}

	public StreamProcessingException(Throwable cause) {
		super(cause);
	}
}
